### ISSUE TITLE
linux-x64 没有那个文件或目录

### ISSUE THREAD

**Issue by zxmacc** [LaoLittle/SkikoMirai#5]
2022-06-23 18:00:27 I/SkikoMirai: 开始下载skiko运行所需库
2022-06-23 18:00:27 E/SkikoMirai: java.lang.UnsatisfiedLinkError: /root/mcl/data/org.laolittle.plugin.SkikoMirai/lib/libskiko-linux-x64.so: libGL.so.1: 无法
打开共享对象文件: 没有那个文件或目录
java.lang.UnsatisfiedLinkError: /root/mcl/data/org.laolittle.plugin.SkikoMirai/lib/libskiko-linux-x64.so: libGL.so.1: 无法打开共享对象文件: 没有那个文件或目
录

iTXTech Mirai Console Loader version 2.1.0-71ec418
![1KZGGZ`P7TA0U`~~0`Q045R](https://user-images.githubusercontent.com/71143103/175274006-203680da-1ffb-47df-9a0a-8dd99fee2eb3.png)

**Comment by zxmacc** [comment]
mirai-console  v2.11.0

**Comment by zxmacc** [comment]
启动好几次了，还是这样，大佬能帮帮忙吗

**Comment by zxmacc** [comment]
已经自行解决，原因是缺少OpenGL开发库，yum install mesa*和yum install freeglut*，就可以正常运行了

**Comment by LaoLittle** [comment]
todo #6
